name: release
on:
  workflow_dispatch:
jobs:
  job-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      - id: generate-sources
        run: mvn verify
      - id: compile-sources
        run: mvn verify -pl source
      - id: publish
        env:
          VERSION: "1.0"
          BUILD: ${{ github.run_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn deploy:deploy-file -DgroupId=me.estrela -DartifactId=emailjs-java-sdk -Dversion=${{ env.VERSION }}.${{ env.BUILD }} -Drevision=${{ env.VERSION }}.${{ env.BUILD }} -Dpackaging=jar -Dfile=source/target/emailjs-java-sdk-${{ env.VERSION }}.jar -DrepositoryId=github -Durl=https://maven.pkg.github.com/rsaestrela/emailjs-java-sdk -DpomFile=pomFile.xml
